### ISSUE TITLE
Update TodosFeed sample to 0.62

### ISSUE THREAD

**Issue by nanduahmed** [microsoft/react-native-windows-samples#101]
When cloning this project and trying running TodosFeed project with _react-native run-windows_ , The console throws the following error 

`error Invalid regular expression: /(C:[\\\]my[\\\]path[\\\]TodosFeed[\\\]TodosFeed[\\\]node_modules[\\\]react-native[\\\].*|C:[\\\]my[\\\]path[\\\]TodosFeed[\\\]TodosFeed[\\\]windows.*|node_modules\\react\\dist\\.*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Range out of order in character class. Run CLI with --verbose flag for more details.`

This is resolved by replacing _metro.config.js_ file from any working react-native-windows project. 

The proper metro.config.js file should be added to the repo or a workaround should be provided

**Comment by chrisglein** [comment]
This is the node version 12 problem. This will go away if we update the TodosFeed sample to 0.62, which... we should do.

**Comment by harinikmsft** [comment]
Updating title to reflect work. @qmatteoq - can you help with the upgrade?

**Comment by qmatteoq** [comment]
It's on my to do list for when I'll be back from vacation 😊 I should be able to work on this next week

**Comment by qmatteoq** [comment]
Done as part of the following PR #158

**Comment by TatianaKapos** [comment]
I'm still seeing this issue running "yarn start", is there a solution to this? thanks! @NickGerleman @qmatteoq

**Comment by chrisglein** [comment]
There's a question about whether the samples should be locked in time to match their blog post, or move forward version to version. Let's discuss that and figure out what to do here.

**Comment by TatianaKapos** [comment]
@chrisglein Here's a current list of the samples we don't upgrade during a release cycle
- AppServiceDemo -> follows an article on our [website](https://microsoft.github.io/react-native-windows/blog/2021/08/05/win32component)
- TodosFeed -> follows a blog post on [Windows AppConsult Blog](https://techcommunity.microsoft.com/t5/windows-dev-appconsult/getting-started-with-react-native-for-windows/ba-p/912093)
- rssreader -> last updated a year and a half ago, still target .62. I think originally we didn't upgrade this was because it also targeted a lower version of MacOS.

If we aren't upgrading these in our release process, we should add that in the READMe's
